# Generated by Django 4.1.5 on 2023-01-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='Products',
            new_name='Ecom_Products',
        ),
    ]
