# Generated by Django 4.1.5 on 2023-01-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_products_cartitems_ecom_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='Ecom_Products',
            new_name='Products',
        ),
    ]
