# Generated by Django 4.1 on 2023-01-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='ecom_Products',
        ),
    ]
