# Generated by Django 4.1.5 on 2023-01-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ecom_products',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
