# Generated by Django 4.1.5 on 2023-01-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecom_products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
